# Generated by Django 4.1.13 on 2024-02-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uploaded_time',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
